/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculadora.h"

void imprimirAyuda()
{
	printf("Sintaxis: <programa> <servidor> <num1> <operador> <num2>\nOperadores disponibles\n+ Suma\n- Resta\nx Producto\n/ División\ne División entera\n%% Modulo\n");
	printf("Para el modo avanzado (operaciones con vectores y matrices, usar la opcion -a: <programa> <servidor> -a");
}

vec3 leerVec3()
{
	printf("Introduce las 3 componentes del vector: ");
	vec3 vector;
	vector.x = scanf("%f");
	vector.y = scanf("%f");
	vector.z = scanf("%f");
	return vector;
}

vec2 leerVec2()
{
	printf("Introduce las 2 componentes del vector: ");
	vec2 vector;
	vector.x = scanf("%f");
	vector.y = scanf("%f");
	return vector;
}

int main(int argc, char **argv)
{
	CLIENT *clnt;
	double *result = NULL;
	int *result_int = NULL;
	pareja_double p_double;
	pareja_int p_int;
	char *host;
	char operacion;
	double num1, num2;

	if (argc != 5 || argc != 3)
	{
		printf("Error de ejecución\n");
		imprimirAyuda();
		exit(-1);
	}
	int avanzado = (argv[3] == "-a") ? 1 : 0;
	host = argv[1];
	num1 = atof(argv[2]);
	num2 = atof(argv[4]);
	operacion = argv[3][0];
#ifndef DEBUG
	clnt = clnt_create(host, CALCULADORA, CALCVER, "udp");
	if (clnt == NULL)
	{
		clnt_pcreateerror(host);
		exit(1);
	}
#endif /* DEBUG */
	if (avanzado == 1)
	{
		switch (operacion)
		{
		case '+':
			p_double.num1 = num1;
			p_double.num2 = num2;
			result = sumar_1(p_double, clnt);
			break;
		case '-':
			p_double.num1 = num1;
			p_double.num2 = num2;
			result = restar_1(p_double, clnt);
			break;
		case 'x':
			p_double.num1 = num1;
			p_double.num2 = num2;
			result = multiplicar_1(p_double, clnt);
			break;
		case '/':
			p_double.num1 = num1;
			p_double.num2 = num2;
			result = dividir_1(p_double, clnt);
			break;
		case 'e':
			p_int.num1 = num1;
			p_int.num2 = num2;
			result_int = divisionentera_1(p_int, clnt);
			break;
		case '%':
			p_int.num1 = num1;
			p_int.num2 = num2;
			result_int = modulo_1(p_int, clnt);
			break;
		default:
			printf("Operador incorrecto\n");
			imprimirAyuda();
			break;
		}

		if ((result == (double *)NULL) && (result_int == (int *)NULL))
		{
			printf("Error en la llamada\n");
			exit(-1);
		}

		if (result != NULL)
		{
			printf("Resultado de %2f %c %2f = %2f\n", num1, operacion, num2, *result);
		}
		else if (result_int != NULL)
		{
			printf("Resultado de %i %s %i = %i\n", (int)num1, argv[3], (int)num2, *result_int);
		}
	}
	else
	{
		printf("Bienvenido al modo avanzado\nSelecciona una operacion:\n1. Suma de vectores\n2. Resta de vectores\n3. Producto escalar\n");
		int eleccion = scanf("%i");
		vec3 v3_1, v3_2;
		vec2 v2_1, v2_2;
		int tipo_vector = 3;

		do
		{
			printf("Selecciona la dimensión del vector (2 o 3): ");
			tipo_vector = scanf("%i");
			if (tipo_vector != 2 || tipo_vector != 3)
			{
				printf("Dimensión no válida\n");
			}
		} while (tipo_vector == 2 || tipo_vector == 3);

		switch (eleccion)
		{
		case 1: 
			if (tipo_vector == 2){
				printf("Leyendo vector 1\n");
				v2_1 = leerVec2();
				printf("Leyendo vector 2\n");
				v2_2 = leerVec2();
			} else{
				printf("Leyendo vector 1\n");
				v3_1 = leerVec3();
				printf("Leyendo vector 2\n");
				v3_2 = leerVec3();
			}
			break;
		case 2:
			if (tipo_vector == 2){
				printf("Leyendo vector 1\n");
				v2_1 = leerVec2();
				printf("Leyendo vector 2\n");
				v2_2 = leerVec2();
			} else{
				printf("Leyendo vector 1\n");
				v3_1 = leerVec3();
				printf("Leyendo vector 2\n");
				v3_2 = leerVec3();
			}
			break;
		case 3:
			double escalar;
			if (tipo_vector == 2){
				printf("Leyendo vector\n");
				v2_1 = leerVec2();
				printf("Introduce el escalar:\n");
				escalar = scanf("%f");
			} else{
				printf("Leyendo vector\n");
				v3_1 = leerVec3();
				printf("Introduce el escalar:\n");
				escalar = scanf("%f");
			}
			break;
		default:
			printf("Error, no es una opción válida\n");
			exit(-1);
			break;
		}
	}
#ifndef DEBUG
	clnt_destroy(clnt);
#endif /* DEBUG */
}
