/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CALCULADORA_H_RPCGEN
#define _CALCULADORA_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define MAX 255

typedef char *nametype;

typedef struct namenode *namelist;

struct sumar_1_argument {
	double num1;
	double num2;
};
typedef struct sumar_1_argument sumar_1_argument;

struct restar_1_argument {
	double num1;
	double num2;
};
typedef struct restar_1_argument restar_1_argument;

struct multiplicar_1_argument {
	double num1;
	double num2;
};
typedef struct multiplicar_1_argument multiplicar_1_argument;

struct dividir_1_argument {
	double num1;
	double num2;
};
typedef struct dividir_1_argument dividir_1_argument;

struct divisionentera_1_argument {
	int num1;
	int num2;
};
typedef struct divisionentera_1_argument divisionentera_1_argument;

#define CALCULADORA 0x20000155
#define CALCVER 1

#if defined(__STDC__) || defined(__cplusplus)
#define SUMAR 1
extern  double * sumar_1(double , double , CLIENT *);
extern  double * sumar_1_svc(double , double , struct svc_req *);
#define RESTAR 2
extern  double * restar_1(double , double , CLIENT *);
extern  double * restar_1_svc(double , double , struct svc_req *);
#define MULTIPLICAR 3
extern  double * multiplicar_1(double , double , CLIENT *);
extern  double * multiplicar_1_svc(double , double , struct svc_req *);
#define DIVIDIR 4
extern  double * dividir_1(double , double , CLIENT *);
extern  double * dividir_1_svc(double , double , struct svc_req *);
#define DIVISIONENTERA 5
extern  double * divisionentera_1(int , int , CLIENT *);
extern  double * divisionentera_1_svc(int , int , struct svc_req *);
extern int calculadora_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define SUMAR 1
extern  double * sumar_1();
extern  double * sumar_1_svc();
#define RESTAR 2
extern  double * restar_1();
extern  double * restar_1_svc();
#define MULTIPLICAR 3
extern  double * multiplicar_1();
extern  double * multiplicar_1_svc();
#define DIVIDIR 4
extern  double * dividir_1();
extern  double * dividir_1_svc();
#define DIVISIONENTERA 5
extern  double * divisionentera_1();
extern  double * divisionentera_1_svc();
extern int calculadora_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_nametype (XDR *, nametype*);
extern  bool_t xdr_namelist (XDR *, namelist*);
extern  bool_t xdr_sumar_1_argument (XDR *, sumar_1_argument*);
extern  bool_t xdr_restar_1_argument (XDR *, restar_1_argument*);
extern  bool_t xdr_multiplicar_1_argument (XDR *, multiplicar_1_argument*);
extern  bool_t xdr_dividir_1_argument (XDR *, dividir_1_argument*);
extern  bool_t xdr_divisionentera_1_argument (XDR *, divisionentera_1_argument*);

#else /* K&R C */
extern bool_t xdr_nametype ();
extern bool_t xdr_namelist ();
extern bool_t xdr_sumar_1_argument ();
extern bool_t xdr_restar_1_argument ();
extern bool_t xdr_multiplicar_1_argument ();
extern bool_t xdr_dividir_1_argument ();
extern bool_t xdr_divisionentera_1_argument ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CALCULADORA_H_RPCGEN */
