/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "calculadora.h"

bool_t
xdr_nametype (XDR *xdrs, nametype *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, objp, MAX))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_namelist (XDR *xdrs, namelist *objp)
{
	register int32_t *buf;

	 if (!xdr_pointer (xdrs, (char **)objp, sizeof (struct namenode), (xdrproc_t) xdr_namenode))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_sumar_1_argument (XDR *xdrs, sumar_1_argument *objp)
{
	 if (!xdr_double (xdrs, &objp->num1))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->num2))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_restar_1_argument (XDR *xdrs, restar_1_argument *objp)
{
	 if (!xdr_double (xdrs, &objp->num1))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->num2))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_multiplicar_1_argument (XDR *xdrs, multiplicar_1_argument *objp)
{
	 if (!xdr_double (xdrs, &objp->num1))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->num2))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_dividir_1_argument (XDR *xdrs, dividir_1_argument *objp)
{
	 if (!xdr_double (xdrs, &objp->num1))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->num2))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_divisionentera_1_argument (XDR *xdrs, divisionentera_1_argument *objp)
{
	 if (!xdr_int (xdrs, &objp->num1))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->num2))
		 return FALSE;
	return TRUE;
}
