/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "calculadora.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

static double *
_sumar_1 (pareja_double  *argp, struct svc_req *rqstp)
{
	return (sumar_1_svc(*argp, rqstp));
}

static double *
_restar_1 (pareja_double  *argp, struct svc_req *rqstp)
{
	return (restar_1_svc(*argp, rqstp));
}

static double *
_multiplicar_1 (pareja_double  *argp, struct svc_req *rqstp)
{
	return (multiplicar_1_svc(*argp, rqstp));
}

static double *
_dividir_1 (pareja_double  *argp, struct svc_req *rqstp)
{
	return (dividir_1_svc(*argp, rqstp));
}

static int *
_divisionentera_1 (pareja_int  *argp, struct svc_req *rqstp)
{
	return (divisionentera_1_svc(*argp, rqstp));
}

static int *
_modulo_1 (pareja_int  *argp, struct svc_req *rqstp)
{
	return (modulo_1_svc(*argp, rqstp));
}

static vec3 *
_sumavec3_1 (pareja_vec3  *argp, struct svc_req *rqstp)
{
	return (sumavec3_1_svc(*argp, rqstp));
}

static vec2 *
_sumavec2_1 (pareja_vec2  *argp, struct svc_req *rqstp)
{
	return (sumavec2_1_svc(*argp, rqstp));
}

static vec3 *
_restavec3_1 (pareja_vec3  *argp, struct svc_req *rqstp)
{
	return (restavec3_1_svc(*argp, rqstp));
}

static vec2 *
_restavec2_1 (pareja_vec2  *argp, struct svc_req *rqstp)
{
	return (restavec2_1_svc(*argp, rqstp));
}

static vec2 *
_pescalar2_1 (vec2escalar  *argp, struct svc_req *rqstp)
{
	return (pescalar2_1_svc(*argp, rqstp));
}

static vec3 *
_pescalar3_1 (vec3escalar  *argp, struct svc_req *rqstp)
{
	return (pescalar3_1_svc(*argp, rqstp));
}

static void
calculadora_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		pareja_double sumar_1_arg;
		pareja_double restar_1_arg;
		pareja_double multiplicar_1_arg;
		pareja_double dividir_1_arg;
		pareja_int divisionentera_1_arg;
		pareja_int modulo_1_arg;
		pareja_vec3 sumavec3_1_arg;
		pareja_vec2 sumavec2_1_arg;
		pareja_vec3 restavec3_1_arg;
		pareja_vec2 restavec2_1_arg;
		vec2escalar pescalar2_1_arg;
		vec3escalar pescalar3_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case SUMAR:
		_xdr_argument = (xdrproc_t) xdr_pareja_double;
		_xdr_result = (xdrproc_t) xdr_double;
		local = (char *(*)(char *, struct svc_req *)) _sumar_1;
		break;

	case RESTAR:
		_xdr_argument = (xdrproc_t) xdr_pareja_double;
		_xdr_result = (xdrproc_t) xdr_double;
		local = (char *(*)(char *, struct svc_req *)) _restar_1;
		break;

	case MULTIPLICAR:
		_xdr_argument = (xdrproc_t) xdr_pareja_double;
		_xdr_result = (xdrproc_t) xdr_double;
		local = (char *(*)(char *, struct svc_req *)) _multiplicar_1;
		break;

	case DIVIDIR:
		_xdr_argument = (xdrproc_t) xdr_pareja_double;
		_xdr_result = (xdrproc_t) xdr_double;
		local = (char *(*)(char *, struct svc_req *)) _dividir_1;
		break;

	case DIVISIONENTERA:
		_xdr_argument = (xdrproc_t) xdr_pareja_int;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) _divisionentera_1;
		break;

	case MODULO:
		_xdr_argument = (xdrproc_t) xdr_pareja_int;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) _modulo_1;
		break;

	case SUMAVEC3:
		_xdr_argument = (xdrproc_t) xdr_pareja_vec3;
		_xdr_result = (xdrproc_t) xdr_vec3;
		local = (char *(*)(char *, struct svc_req *)) _sumavec3_1;
		break;

	case SUMAVEC2:
		_xdr_argument = (xdrproc_t) xdr_pareja_vec2;
		_xdr_result = (xdrproc_t) xdr_vec2;
		local = (char *(*)(char *, struct svc_req *)) _sumavec2_1;
		break;

	case RESTAVEC3:
		_xdr_argument = (xdrproc_t) xdr_pareja_vec3;
		_xdr_result = (xdrproc_t) xdr_vec3;
		local = (char *(*)(char *, struct svc_req *)) _restavec3_1;
		break;

	case RESTAVEC2:
		_xdr_argument = (xdrproc_t) xdr_pareja_vec2;
		_xdr_result = (xdrproc_t) xdr_vec2;
		local = (char *(*)(char *, struct svc_req *)) _restavec2_1;
		break;

	case PESCALAR2:
		_xdr_argument = (xdrproc_t) xdr_vec2escalar;
		_xdr_result = (xdrproc_t) xdr_vec2;
		local = (char *(*)(char *, struct svc_req *)) _pescalar2_1;
		break;

	case PESCALAR3:
		_xdr_argument = (xdrproc_t) xdr_vec3escalar;
		_xdr_result = (xdrproc_t) xdr_vec3;
		local = (char *(*)(char *, struct svc_req *)) _pescalar3_1;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	pmap_unset (CALCULADORA, CALCVER);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, CALCULADORA, CALCVER, calculadora_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (CALCULADORA, CALCVER, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, CALCULADORA, CALCVER, calculadora_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (CALCULADORA, CALCVER, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
