/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculadora.h"


void
calculadora_1(char *host)
{
	CLIENT *clnt;
	double  *result_1;
	double sumar_1_num1;
	double sumar_1_num2;
	double  *result_2;
	double restar_1_num1;
	double restar_1_num2;
	double  *result_3;
	double multiplicar_1_num1;
	double multiplicar_1_num2;
	double  *result_4;
	double dividir_1_num1;
	double dividir_1_num2;
	double  *result_5;
	int divisionentera_1_num1;
	int divisionentera_1_num2;

#ifndef	DEBUG
	clnt = clnt_create (host, CALCULADORA, CALCVER, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = sumar_1(sumar_1_num1, sumar_1_num2, clnt);
	if (result_1 == (double *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_2 = restar_1(restar_1_num1, restar_1_num2, clnt);
	if (result_2 == (double *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_3 = multiplicar_1(multiplicar_1_num1, multiplicar_1_num2, clnt);
	if (result_3 == (double *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_4 = dividir_1(dividir_1_num1, dividir_1_num2, clnt);
	if (result_4 == (double *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_5 = divisionentera_1(divisionentera_1_num1, divisionentera_1_num2, clnt);
	if (result_5 == (double *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	calculadora_1 (host);
exit (0);
}
